#include <ESP8266WiFi.h>
#include <ESP8266WebServer.h>
#include <LittleFS.h>
#include <EEPROM.h>
#include <stdlib.h>
#include <string.h>

// ESP8266 is only a Wi-Fi/web HMI and logger. Mega remains the controller.
const unsigned long UART_BAUD=115200UL, MEGA_TIMEOUT=5000UL, WIFI_TIMEOUT=15000UL, WIFI_RETRY=30000UL, LOG_INTERVAL=60000UL;
const size_t RX_SIZE=640;
const char DEFAULT_SSID[]="STRONG", DEFAULT_PASS[]="<REDACTED>";
const char AP_SSID[]="BAZEN-CONFIG", AP_PASS[]="<REDACTED>";
const IPAddress WIFI_STATIC_IP(192,168,0,50);
const IPAddress WIFI_GATEWAY(192,168,0,1);
const IPAddress WIFI_SUBNET(255,255,255,0);
const IPAddress WIFI_DNS(192,168,0,1);
ESP8266WebServer server(80);

struct WifiCfg { uint32_t magic; char ssid[33]; char pass[65]; uint32_t crc; } cfg;
// New magic intentionally makes the supplied STRONG configuration effective
// after this firmware is installed; /config can subsequently store a new one.
const uint32_t CFG_MAGIC=0x425A5732UL;
bool cfgStored=false,wifiConnecting=false,apRunning=false,wasConnected=false,fsReady=false,fsWriteError=false;
unsigned long wifiStarted=0,wifiLastTry=0,lastLog=0;

struct FV { float v; bool ok; };
struct Snapshot {
  FV t1,t2,t3,t4,tbox,out,rh,bazen,set,setmin,setmax;
  char sys[10],mode[10],time[9],date[11];
  int8_t solar,fil,filman,chr,ulink,magr,uagr,r[16];
} data;
bool haveData=false,megaOnline=false;
unsigned long lastData=0;
char rx[RX_SIZE],json[3000]; size_t rxLen=0; bool rxOverflow=false;

const char PAGE[] PROGMEM=R"HTML(<!doctype html><html lang="sk"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Bazén</title><style>
:root{color-scheme:dark;--bg:#071521;--card:#102838;--line:#285064;--fg:#effaff;--muted:#91adbb;--ok:#35d07f;--bad:#ff5d68;--a:#38bdf8}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--fg);font:16px system-ui}.w{max-width:1100px;margin:auto;padding:14px}.top{display:flex;justify-content:space-between;align-items:center;gap:10px;flex-wrap:wrap}.badge{background:var(--bad);padding:9px 13px;border-radius:99px;font-weight:800}.badge.on{background:var(--ok);color:#042114}.stale{display:none;margin:12px 0;padding:12px;border:1px solid var(--bad);border-radius:10px;background:#5b1c23;font-weight:700}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:12px}.card{background:var(--card);border:1px solid var(--line);border-radius:14px;padding:16px}.card h2{font-size:1rem;color:var(--a);margin:0 0 12px}.rows{display:grid;grid-template-columns:1fr auto;gap:9px}.big{font-size:2rem;font-weight:800}.controls{display:flex;align-items:center;justify-content:center;gap:10px;flex-wrap:wrap}button{padding:12px 16px;border:0;border-radius:9px;background:var(--a);font-weight:800}button:disabled{opacity:.35}.step{font-size:1.5rem}.edit{font-size:1.6rem;min-width:105px;text-align:center}.ok{color:var(--ok)}.bad{color:var(--bad)}a{color:var(--a);margin-right:12px}#msg{text-align:center;color:#fbbf24;min-height:1.3em}
</style></head><body><main class="w"><div class="top"><div><h1>Bazén automatika</h1><a href="/logs">Teplotné logy</a><a href="/errors">Chyby a diagnostika</a><a href="/config">Wi‑Fi</a></div><b id="mega" class="badge">MEGA OFFLINE</b></div><div id="stale" class="stale">Údaje sú neaktuálne. Ovládanie je zablokované.</div><div class="grid">
<section class="card"><h2>REGULÁCIA BAZÉNA</h2><div class="rows"><span>Aktuálna regulačná</span><span id="BAZEN" class="big">—</span><span>MAX teplota</span><span id="SET">—</span><span>Systém</span><span id="SYS">—</span><span>Režim</span><span id="MODE">—</span></div></section>
<section class="card"><h2>TEPLOTY A SENZORY</h2><div class="rows"><span>T1 – bazén</span><span id="T1">—</span><span>T2 – solárny výstup</span><span id="T2">—</span><span>T3 – panel</span><span id="T3">—</span><span>T4 – dno bazéna</span><span id="T4">—</span><span>TBOX</span><span id="TBOX">—</span><span>Vonku</span><span id="OUT">—</span><span>Vlhkosť vonku</span><span id="RH">—</span></div></section>
<section class="card"><h2>PREVÁDZKA</h2><div class="rows"><span>Solár</span><span id="SOLAR">—</span><span>Filtrácia</span><span id="FIL">—</span><span>Manuálna filtrácia 6 h</span><span id="FILMAN">—</span><span>Chrlič 1 h</span><span id="CHR">—</span><span>UNO chrlič</span><span>NEIMPLEMENTOVANÉ</span><span>UNO preplach</span><span>NEIMPLEMENTOVANÉ</span></div></section>
<section class="card"><h2>MEGA ↔ UNO</h2><div class="rows"><span>Link</span><span id="ULINK">—</span><span>Mega agreement</span><span id="MAGR">—</span><span>UNO agreement</span><span id="UAGR">—</span><span>Čas / dátum</span><span id="CLOCK">—</span></div></section>
<section class="card"><h2>OVLÁDANIE</h2><div class="controls"><button class="ctl step" id="minus">−</button><span id="edit" class="edit">—</span><button class="ctl step" id="plus">+</button><button class="ctl" id="set">Potvrdiť MAX teplotu</button></div><hr><div class="controls"><button class="ctl" id="filb">Manuálna filtrácia 6 h</button><button class="ctl" id="chrb">Chrlič 1 h</button></div><p id="msg"></p></section>
</div></main><script>
let ev=null,lo=null,hi=null,editing=false,busy=false;const $=x=>document.getElementById(x),dash='—',fv=(v,u)=>v===null?'CHYBA':Number(v).toFixed(1)+(u||''),bv=v=>v===null?'NEDOSTUPNÉ':v?'ON':'OFF';
function put(k,v,u){let e=$(k);e.textContent=fv(v,u);e.className=v===null?'bad':'ok'}
function enable(on){document.querySelectorAll('.ctl').forEach(x=>x.disabled=!on||busy)}
async function refresh(){try{let d=await(await fetch('/api/status',{cache:'no-store'})).json(),on=d.megaOnline;$('mega').textContent=on?'MEGA ONLINE':'MEGA OFFLINE';$('mega').classList.toggle('on',on);$('stale').style.display=on?'none':'block';enable(on);['T1','T2','T3','T4','TBOX','OUT','BAZEN','SET'].forEach(k=>put(k,d[k],' °C'));put('RH',d.RH,' %');$('SYS').textContent=d.SYS??dash;$('MODE').textContent=d.MODE??dash;['SOLAR','FIL','FILMAN','CHR','ULINK','MAGR','UAGR'].forEach(k=>$(k).textContent=bv(d[k]));$('CLOCK').textContent=(d.TIME??dash)+'  '+(d.DATE??dash);if(d.SETMIN!==null)lo=+d.SETMIN;if(d.SETMAX!==null)hi=+d.SETMAX;if(!editing&&d.SET!==null){ev=+d.SET;$('edit').textContent=ev.toFixed(1)+' °C'}}catch(e){$('mega').textContent='MEGA OFFLINE';$('mega').classList.remove('on');$('stale').style.display='block';enable(false)}}
function step(n){if(ev===null||lo===null||hi===null||busy)return;ev=Math.min(hi,Math.max(lo,Math.round((ev+n)*10)/10));editing=true;$('edit').textContent=ev.toFixed(1)+' °C'}
async function post(u,b=''){if(busy)return;busy=true;enable(false);try{let r=await fetch(u,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:b});$('msg').textContent=await r.text();await new Promise(x=>setTimeout(x,600));await refresh()}catch(e){$('msg').textContent='Chyba spojenia s web HMI'}finally{busy=false;editing=false;setTimeout(()=>{$('msg').textContent='';refresh()},1800)}}
$('minus').onclick=()=>step(-.1);$('plus').onclick=()=>step(.1);$('set').onclick=()=>{if(ev!==null)post('/api/settemp','value='+ev.toFixed(1))};$('filb').onclick=()=>post('/api/fil6h');$('chrb').onclick=()=>post('/api/chr1h');refresh();setInterval(refresh,1000);
</script></body></html>)HTML";

const char ERRORS_PAGE[] PROGMEM=R"HTML(<!doctype html><html lang="sk"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Chyby</title><style>body{max-width:760px;margin:28px auto;padding:16px;background:#071521;color:#effaff;font:17px system-ui}.c{background:#102838;border:1px solid #285064;border-radius:12px;padding:16px;margin:12px 0}.ok{color:#35d07f}.bad{color:#ff5d68}a{color:#38bdf8}</style><h1>Chyby a diagnostika</h1><p><a href="/">Späť na hlavný prehľad</a></p><div id="x" class="c">Načítavam…</div><script>const n=x=>x===null||x===undefined;async function r(){try{let d=await(await fetch('/api/status',{cache:'no-store'})).json(),a=[];['T1','T2','T3','T4','TBOX','OUT','RH'].forEach(k=>{if(n(d[k]))a.push(k+': NEPLATNÝ / NEDOSTUPNÝ')});if(!d.megaOnline)a.push('MEGA Wi‑Fi telemetria: NEAKTUÁLNA');if(d.ULINK!==true)a.push('Mega↔Uno link: CHYBA alebo nedostupný');if(d.MAGR!==true)a.push('Mega agreement: OFF');if(d.UAGR!==true)a.push('UNO agreement: OFF');let mode=d.MODE||'NEDOSTUPNÝ',sys=d.SYS||'NEDOSTUPNÝ';document.getElementById('x').innerHTML='<b>SYS: '+sys+' | MODE: '+mode+'</b><hr>'+(a.length?'<ul class="bad"><li>'+a.join('</li><li>')+'</li></ul>':'<b class="ok">Žiadna telemetrická chyba.</b>')+'<p>UNO chrlič a preplach dnes nie sú implementované stavy.</p>'}catch(e){document.getElementById('x').textContent='Web HMI nedokáže načítať aktuálne údaje.'}}r();setInterval(r,2000)</script>)HTML";

const char LOGS_PAGE[] PROGMEM=R"HTML(<!doctype html><html lang="sk"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Teplotné logy</title><style>body{max-width:1100px;margin:20px auto;padding:14px;background:#071521;color:#effaff;font:16px system-ui}a,button{color:#071521;background:#38bdf8;padding:9px;border-radius:7px;border:0;text-decoration:none;font-weight:bold;margin:3px}input{padding:8px}canvas{width:100%;height:300px;background:#102838;border:1px solid #285064}table{border-collapse:collapse;width:100%;font-size:13px}td,th{padding:4px;border-bottom:1px solid #285064;text-align:right}td:first-child,th:first-child{text-align:left}#msg{margin:12px 0}</style><h1>Teplotné logy</h1><p><a href="/">Späť</a><button id="today">Dnes</button><button id="prev">← predchádzajúci</button><input id="day" type="date"><button id="next">nasledujúci →</button></p><div id="msg">Načítavam zoznam dní…</div><canvas id="g" width="1000" height="300"></canvas><table><thead><tr><th>Čas</th><th>T1</th><th>T2</th><th>T3</th><th>T4</th><th>Vonku</th><th>MAX</th></tr></thead><tbody id="rows"></tbody></table><script>
let days=[],cur='';const q=x=>document.querySelector(x);function graph(rows){let c=q('#g'),x=c.getContext('2d'),w=c.width,h=c.height;x.clearRect(0,0,w,h);let ks=[1,2,3,4,5,6],cols=['#38bdf8','#fbbf24','#fb7185','#a78bfa','#34d399','#fff'],vs=[];rows.forEach(r=>ks.forEach(k=>{let v=parseFloat(r[k]);if(!isNaN(v))vs.push(v)}));if(!vs.length)return;let mn=Math.floor(Math.min(...vs)-1),mx=Math.ceil(Math.max(...vs)+1),N=Math.max(rows.length-1,1);x.strokeStyle='#618';x.strokeRect(0,0,w-1,h-1);ks.forEach((k,j)=>{x.strokeStyle=cols[j];x.beginPath();let pen=false;rows.forEach((r,i)=>{let v=parseFloat(r[k]);if(isNaN(v)){pen=false;return}let px=i*w/N,py=h-(v-mn)/(mx-mn)*h;if(!pen){x.moveTo(px,py);pen=true}else x.lineTo(px,py)});x.stroke()});x.fillStyle='#effaff';x.fillText(mn+' °C',4,h-5);x.fillText(mx+' °C',4,12)}
async function load(){if(!cur)return;q('#day').value=cur;q('#msg').textContent='Načítavam '+cur+'…';let r=await fetch('/api/log?date='+cur);if(!r.ok){q('#msg').textContent='Pre tento deň nie sú uložené dáta.';q('#rows').innerHTML='';return}let t=await r.text(),lines=t.trim().split('\n').slice(1),rows=lines.filter(Boolean).map(x=>x.split(','));q('#msg').textContent='Denný log: '+rows.length+' záznamov (interval 1 minúta).';q('#rows').innerHTML=rows.map(r=>'<tr>'+r.map(v=>'<td>'+v+'</td>').join('')+'</tr>').join('');graph(rows)}
function choose(i){if(i>=0&&i<days.length){cur=days[i];load()}}async function init(){days=await(await fetch('/api/logdays')).json();days.sort();let s=await(await fetch('/api/status')).json(),today=s.DATE? s.DATE.slice(6,10)+'-'+s.DATE.slice(3,5)+'-'+s.DATE.slice(0,2):'';cur=days.includes(today)?today:(days[days.length-1]||'');q('#day').value=cur;q('#msg').textContent=cur?'':'Nie je dostupný žiadny uložený denný log.';if(cur)load()}q('#today').onclick=()=>{let v=q('#day').value;let i=days.indexOf(v);if(i>=0)choose(i)};q('#prev').onclick=()=>choose(days.indexOf(cur)-1);q('#next').onclick=()=>choose(days.indexOf(cur)+1);q('#day').onchange=()=>{if(days.includes(q('#day').value)){cur=q('#day').value;load()}else q('#msg').textContent='Pre zvolený deň nie je uložený log.'};init();
</script>)HTML";

const char CONFIG_PAGE[] PROGMEM=R"HTML(<!doctype html><html lang="sk"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Wi‑Fi</title><style>body{max-width:520px;margin:40px auto;padding:18px;background:#071521;color:#eefaff;font:17px system-ui}form{background:#102838;padding:22px;border-radius:14px}label,input{display:block;width:100%;margin:9px 0}input{padding:12px}button{padding:12px;background:#38bdf8;border:0;border-radius:8px;font-weight:bold}a{color:#38bdf8}</style><h1>Wi‑Fi konfigurácia</h1><p>Konfiguračný AP: <b>BAZEN-CONFIG</b></p><form method="post" action="/config"><label>SSID<input name="ssid" maxlength="32" required></label><label>Heslo<input name="password" type="password" maxlength="64"></label><button>Uložiť a pripojiť</button></form><p><a href="/">Späť</a></p>)HTML";

uint32_t checksum(const WifiCfg&c){const uint8_t*p=(const uint8_t*)&c;uint32_t h=2166136261UL;for(size_t i=0;i<offsetof(WifiCfg,crc);i++)h=(h^p[i])*16777619UL;return h;}
void loadConfig(){EEPROM.begin(sizeof(WifiCfg));EEPROM.get(0,cfg);cfgStored=cfg.magic==CFG_MAGIC&&cfg.ssid[0]&&cfg.ssid[32]=='\0'&&cfg.pass[64]=='\0'&&cfg.crc==checksum(cfg);if(!cfgStored){memset(&cfg,0,sizeof(cfg));cfg.magic=CFG_MAGIC;strncpy(cfg.ssid,DEFAULT_SSID,32);strncpy(cfg.pass,DEFAULT_PASS,64);}}
bool saveConfig(const char*s,const char*p){size_t a=strlen(s),b=strlen(p);if(!a||a>32||b>64)return false;memset(&cfg,0,sizeof(cfg));cfg.magic=CFG_MAGIC;memcpy(cfg.ssid,s,a);memcpy(cfg.pass,p,b);cfg.crc=checksum(cfg);EEPROM.put(0,cfg);cfgStored=EEPROM.commit();return cfgStored;}
void startAP(){if(apRunning)return;WiFi.mode(WIFI_AP_STA);WiFi.softAP(AP_SSID,AP_PASS);apRunning=true;Serial.println("CONFIG AP START");}
void connectWifi(){WiFi.mode(apRunning?WIFI_AP_STA:WIFI_STA);WiFi.config(WIFI_STATIC_IP,WIFI_GATEWAY,WIFI_SUBNET,WIFI_DNS);WiFi.begin(cfg.ssid,cfg.pass);wifiConnecting=true;wifiStarted=wifiLastTry=millis();}
void updateWifi(){bool on=WiFi.status()==WL_CONNECTED;if(on&&!wasConnected){wasConnected=true;wifiConnecting=false;Serial.println("WiFi connected");Serial.println(WiFi.localIP());if(apRunning){WiFi.softAPdisconnect(true);apRunning=false;WiFi.mode(WIFI_STA);}}else if(!on&&wasConnected){wasConnected=false;Serial.println("WiFi disconnected");}if(!on&&wifiConnecting&&millis()-wifiStarted>=WIFI_TIMEOUT){wifiConnecting=false;startAP();}if(!on&&!wifiConnecting&&millis()-wifiLastTry>=WIFI_RETRY)connectWifi();}

bool pf(const char*s,FV&o){if(!strcmp(s,"NA")){o.ok=false;o.v=0;return true;}char*e;float v=strtof(s,&e);if(!*s||*e||isnan(v)||isinf(v))return false;o.ok=true;o.v=v;return true;}
bool pb(const char*s,int8_t&o,bool na=false){if(na&&!strcmp(s,"NA")){o=-1;return true;}if(!strcmp(s,"0")){o=0;return true;}if(!strcmp(s,"1")){o=1;return true;}return false;}
bool validTime(const char*s){return !strcmp(s,"NA")||(strlen(s)==8&&s[2]==':'&&s[5]==':');}bool validDate(const char*s){if(!strcmp(s,"NA"))return true;if(strlen(s)!=10||s[2]!='.'||s[5]!='.')return false;for(byte i=0;i<10;i++)if(i!=2&&i!=5&&(s[i]<'0'||s[i]>'9'))return false;return true;}
void optionalField(const char*k,const char*v,Snapshot&n){if(!strcmp(k,"TBOX"))pf(v,n.tbox);else if(!strcmp(k,"SETMIN"))pf(v,n.setmin);else if(!strcmp(k,"SETMAX"))pf(v,n.setmax);else if(!strcmp(k,"ULINK"))pb(v,n.ulink);else if(!strcmp(k,"MAGR"))pb(v,n.magr);else if(!strcmp(k,"UAGR"))pb(v,n.uagr);else if(!strcmp(k,"MODE")&&strlen(v)<sizeof(n.mode))strcpy(n.mode,v);}
bool parseLine(char*line){Snapshot n;memset(&n,0,sizeof(n));n.solar=n.fil=n.filman=n.chr=n.ulink=n.magr=n.uagr=-1;for(byte i=0;i<16;i++)n.r[i]=-1;uint64_t seen=0;char*save=NULL;char*t=strtok_r(line,";",&save);if(!t||strcmp(t,"DATA"))return false;while((t=strtok_r(NULL,";",&save))){char*eq=strchr(t,'=');if(!eq)return false;*eq++='\0';int bit=-1;bool ok=true;if(!strcmp(t,"VER")){bit=0;ok=!strcmp(eq,"1");}else if(!strcmp(t,"T1")){bit=1;ok=pf(eq,n.t1);}else if(!strcmp(t,"T2")){bit=2;ok=pf(eq,n.t2);}else if(!strcmp(t,"T3")){bit=3;ok=pf(eq,n.t3);}else if(!strcmp(t,"T4")){bit=4;ok=pf(eq,n.t4);}else if(!strcmp(t,"OUT")){bit=5;ok=pf(eq,n.out);}else if(!strcmp(t,"RH")){bit=6;ok=pf(eq,n.rh);}else if(!strcmp(t,"BAZEN")){bit=7;ok=pf(eq,n.bazen);}else if(!strcmp(t,"SET")){bit=8;ok=pf(eq,n.set);}else if(!strcmp(t,"SYS")){bit=9;ok=!strcmp(eq,"OK")||!strcmp(eq,"DEGRADED")||!strcmp(eq,"HAVARIA");if(ok)strncpy(n.sys,eq,9);}else if(!strcmp(t,"SOLAR")){bit=10;ok=pb(eq,n.solar);}else if(!strcmp(t,"FIL")){bit=11;ok=pb(eq,n.fil);}else if(!strcmp(t,"FILMAN")){bit=12;ok=pb(eq,n.filman);}else if(!strcmp(t,"CHR")){bit=13;ok=pb(eq,n.chr);}else if(t[0]=='R'){char*e;long r=strtol(t+1,&e,10);if(!*e&&r>=1&&r<=16){bit=13+r;ok=pb(eq,n.r[r-1],true);}}else if(!strcmp(t,"TIME")){bit=30;ok=validTime(eq);if(ok)strncpy(n.time,eq,8);}else if(!strcmp(t,"DATE")){bit=31;ok=validDate(eq);if(ok)strncpy(n.date,eq,10);}else optionalField(t,eq,n);if(!ok)return false;if(bit>=0)seen|=1ULL<<bit;}if(seen!=0xFFFFFFFFULL)return false;data=n;haveData=true;lastData=millis();if(!megaOnline){megaOnline=true;Serial.println("MEGA ONLINE");}return true;}
void updateUart(){while(Serial.available()){char c=Serial.read();if(c=='\n'){if(!rxOverflow&&rxLen){rx[rxLen]='\0';parseLine(rx);}rxLen=0;rxOverflow=false;}else if(c!='\r'&&!rxOverflow){if(rxLen<RX_SIZE-1)rx[rxLen++]=c;else rxOverflow=true;}}if(megaOnline&&millis()-lastData>=MEGA_TIMEOUT){megaOnline=false;Serial.println("MEGA OFFLINE");}}

const char*jf(char*b,size_t z,const FV&v){if(!v.ok)strncpy(b,"null",z);else snprintf(b,z,"%.1f",v.v);b[z-1]='\0';return b;}const char*jb(int8_t v){return v<0?"null":v?"true":"false";}const char*js(const char*s){return s&&s[0]?s:"";}
void statusApi(){char a[16],b[16],c[16],d[16],e[16],f[16],g[16],h[16],i[16],j[16],k[16];size_t p=snprintf(json,sizeof(json),"{\"megaOnline\":%s,\"T1\":%s,\"T2\":%s,\"T3\":%s,\"T4\":%s,\"TBOX\":%s,\"OUT\":%s,\"RH\":%s,\"BAZEN\":%s,\"SET\":%s,\"SETMIN\":%s,\"SETMAX\":%s,\"SYS\":\"%s\",\"MODE\":\"%s\",\"SOLAR\":%s,\"FIL\":%s,\"FILMAN\":%s,\"CHR\":%s,\"ULINK\":%s,\"MAGR\":%s,\"UAGR\":%s",megaOnline?"true":"false",jf(a,16,data.t1),jf(b,16,data.t2),jf(c,16,data.t3),jf(d,16,data.t4),jf(e,16,data.tbox),jf(f,16,data.out),jf(g,16,data.rh),jf(h,16,data.bazen),jf(i,16,data.set),jf(j,16,data.setmin),jf(k,16,data.setmax),js(data.sys),js(data.mode),jb(data.solar),jb(data.fil),jb(data.filman),jb(data.chr),jb(data.ulink),jb(data.magr),jb(data.uagr));for(byte n=0;n<16;n++)p+=snprintf(json+p,sizeof(json)-p,",\"R%u\":%s",n+1,jb(data.r[n]));const char*tm=haveData&&strcmp(data.time,"NA")?data.time:NULL,*dt=haveData&&strcmp(data.date,"NA")?data.date:NULL;snprintf(json+p,sizeof(json)-p,",\"TIME\":%s%s%s,\"DATE\":%s%s%s,\"LOGFS\":%s,\"LOGERR\":%s}",tm?"\"":"",tm?tm:"null",tm?"\"":"",dt?"\"":"",dt?dt:"null",dt?"\"":"",fsReady?"true":"false",fsWriteError?"true":"false");server.sendHeader("Cache-Control","no-store");server.send(200,"application/json",json);}
bool canCommand(){if(megaOnline)return true;server.send(503,"text/plain","MEGA OFFLINE");return false;}
void setTemp(){if(!canCommand())return;if(!server.hasArg("value")){server.send(400,"text/plain","Chýba hodnota");return;}String s=server.arg("value");char*e;float v=strtof(s.c_str(),&e);if(!s.length()||*e||isnan(v)||isinf(v)||!data.setmin.ok||!data.setmax.ok||v<data.setmin.v||v>data.setmax.v){server.send(400,"text/plain","Hodnota je mimo limitu Mega");return;}int x=lroundf(v*10);char cmd[24];snprintf(cmd,sizeof(cmd),"SETTEMP=%d.%d",x/10,abs(x%10));Serial.println(cmd);server.send(202,"text/plain","Príkaz odoslaný, čakám na potvrdenie Mega");}
void toggle(const char*cmd){if(!canCommand())return;Serial.println(cmd);server.send(202,"text/plain","Príkaz odoslaný, čakám na potvrdenie Mega");}

bool datePath(const char*iso,char*path,size_t z){if(strlen(iso)!=10||iso[4]!='-'||iso[7]!='-')return false;for(byte n=0;n<10;n++)if(n!=4&&n!=7&&(iso[n]<'0'||iso[n]>'9'))return false;snprintf(path,z,"/log_%c%c%c%c%c%c%c%c.csv",iso[0],iso[1],iso[2],iso[3],iso[5],iso[6],iso[8],iso[9]);return true;}
bool telemetryDay(char*iso,size_t z){if(!haveData||!validDate(data.date)||!strcmp(data.date,"NA"))return false;snprintf(iso,z,"20%c%c-%c%c-%c%c",data.date[6],data.date[7],data.date[3],data.date[4],data.date[0],data.date[1]);return true;}
void csvField(File&f,const FV&v){if(v.ok)f.print(v.v,1);else f.print("NA");}
void updateLogger(){if(!fsReady||!megaOnline||millis()-lastLog<LOG_INTERVAL)return;lastLog=millis();char day[11],path[24];if(!telemetryDay(day,sizeof(day))||!datePath(day,path,sizeof(path)))return;File f=LittleFS.open(path,"a");if(!f){fsWriteError=true;Serial.println("LOG: FS WRITE ERROR");return;}if(f.size()==0)f.println("time,T1,T2,T3,T4,OUT,SET");if(data.time[0]&&strcmp(data.time,"NA"))f.print(data.time);else f.print("NA");f.print(',');csvField(f,data.t1);f.print(',');csvField(f,data.t2);f.print(',');csvField(f,data.t3);f.print(',');csvField(f,data.t4);f.print(',');csvField(f,data.out);f.print(',');csvField(f,data.set);f.println();f.close();fsWriteError=false;}
void apiDays(){String out="[";bool first=true;Dir d=LittleFS.openDir("/");while(d.next()){String n=d.fileName();if(n.length()==17&&n.startsWith("/log_")&&n.endsWith(".csv")){String iso=n.substring(5,9)+"-"+n.substring(9,11)+"-"+n.substring(11,13);if(!first)out+=',';out+='"'+iso+'"';first=false;}}out+=']';server.send(200,"application/json",out);}
void apiLog(){if(!server.hasArg("date")){server.send(400,"text/plain","Chýba dátum");return;}char p[24];String d=server.arg("date");if(!datePath(d.c_str(),p,sizeof(p))){server.send(400,"text/plain","Neplatný dátum");return;}File f=LittleFS.open(p,"r");if(!f){server.send(404,"text/plain","Log neexistuje");return;}server.streamFile(f,"text/csv");f.close();}
void configPost(){if(!server.hasArg("ssid")||!server.hasArg("password")){server.send(400,"text/plain","Chýbajú údaje");return;}String s=server.arg("ssid"),p=server.arg("password");if(!saveConfig(s.c_str(),p.c_str())){server.send(400,"text/plain","Neplatné údaje alebo chyba flash");return;}server.send(200,"text/html; charset=utf-8","<h2>Uložené. ESP sa pripája k novej sieti.</h2>");WiFi.disconnect();connectWifi();}
void setupWeb(){server.on("/",HTTP_GET,[](){server.send_P(200,"text/html; charset=utf-8",PAGE);});server.on("/errors",HTTP_GET,[](){server.send_P(200,"text/html; charset=utf-8",ERRORS_PAGE);});server.on("/logs",HTTP_GET,[](){server.send_P(200,"text/html; charset=utf-8",LOGS_PAGE);});server.on("/api/status",HTTP_GET,statusApi);server.on("/api/logdays",HTTP_GET,apiDays);server.on("/api/log",HTTP_GET,apiLog);server.on("/api/settemp",HTTP_POST,setTemp);server.on("/api/fil6h",HTTP_POST,[](){toggle("FIL6H=TOGGLE");});server.on("/api/chr1h",HTTP_POST,[](){toggle("CHR1H=TOGGLE");});server.on("/config",HTTP_GET,[](){server.send_P(200,"text/html; charset=utf-8",CONFIG_PAGE);});server.on("/config",HTTP_POST,configPost);server.onNotFound([](){server.send(404,"text/plain","Not found");});server.begin();}
void setup(){Serial.begin(UART_BAUD);data.solar=data.fil=data.filman=data.chr=data.ulink=data.magr=data.uagr=-1;for(byte n=0;n<16;n++)data.r[n]=-1;loadConfig();fsReady=LittleFS.begin();if(!fsReady)Serial.println("LOG: LittleFS NEDOSTUPNY");connectWifi();setupWeb();}
void loop(){updateUart();updateWifi();updateLogger();server.handleClient();yield();}